server:
  port: 8080
  servlet:
    context-path: /api/v1/sweet-store
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://sweet-store-pgsql.ce6tfsyepdjw.us-east-1.rds.amazonaws.com:5432/postgres?charSet=LATIN1
    username: postgres
    password: sweetstore
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
sweetstock:
  domain: localhost
  path: /v1/sweet-stock/
  port: 8080
