server:
  port: 8080
  servlet:
    context-path: /api/v1/sweet-store
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sweetstore?charSet=LATIN1
    username: postgres
    password: sweetstore
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true